[0m15:09:28.891711 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c47bc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10543e5a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10543e090>]}


============================== 15:09:28.897135 | ff217e88-6e29-4393-9503-8f8247aa21c4 ==============================
[0m15:09:28.897135 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:09:28.900851 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/mirnawong/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m15:09:28.942545 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b6ade0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d3e540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d3e030>]}


============================== 15:09:28.945817 | 57a4286a-17b9-43e1-9fd5-48ddb951000a ==============================
[0m15:09:28.945817 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:09:28.946169 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mirnawong/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m15:09:28.950436 [error] [MainThread]: Encountered an error:
Runtime Error
  The 'packages' key cannot be specified in both packages.yml and dependencies.yml
[0m15:09:28.952518 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.14230025, "process_in_blocks": "0", "process_kernel_time": 0.139326, "process_mem_max_rss": "89948160", "process_out_blocks": "0", "process_user_time": 0.861063}
[0m15:09:28.952900 [debug] [MainThread]: Command `cli deps` failed at 15:09:28.952829 after 0.14 seconds
[0m15:09:28.953122 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100cceb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1051aa4b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100d12a80>]}
[0m15:09:28.953323 [debug] [MainThread]: Flushing usage events
[0m15:09:28.952117 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a930e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10923a510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10923a000>]}


============================== 15:09:28.957585 | 60931134-6db1-49c2-85ff-b41d79c7a575 ==============================
[0m15:09:28.957585 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:09:28.957958 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mirnawong/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:09:29.001104 [error] [MainThread]: Encountered an error:
Runtime Error
  The 'packages' key cannot be specified in both packages.yml and dependencies.yml
[0m15:09:29.002317 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.13006912, "process_in_blocks": "0", "process_kernel_time": 0.143119, "process_mem_max_rss": "89784320", "process_out_blocks": "0", "process_user_time": 0.887866}
[0m15:09:29.002840 [debug] [MainThread]: Command `cli deps` failed at 15:09:29.002728 after 0.13 seconds
[0m15:09:29.003345 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1024aeb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106c18bf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d3ccb0>]}
[0m15:09:29.003811 [debug] [MainThread]: Flushing usage events
[0m15:09:29.010926 [error] [MainThread]: Encountered an error:
Runtime Error
  The 'packages' key cannot be specified in both packages.yml and dependencies.yml
[0m15:09:29.012464 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.14630046, "process_in_blocks": "0", "process_kernel_time": 0.142097, "process_mem_max_rss": "91193344", "process_out_blocks": "0", "process_user_time": 0.851706}
[0m15:09:29.013090 [debug] [MainThread]: Command `cli deps` failed at 15:09:29.013012 after 0.15 seconds
[0m15:09:29.013315 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c82f60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10835c320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10923a420>]}
[0m15:09:29.013648 [debug] [MainThread]: Flushing usage events
[0m15:09:29.757901 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:09:29.759620 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:09:29.772901 [debug] [MainThread]: An error was encountered while trying to flush usage events
